#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';

const token = process.env.FIGMA_ACCESS_TOKEN;
const fileKey = process.env.FIGMA_FILE_KEY;
const nodeIdsRaw = process.env.FIGMA_COMPONENT_NODE_IDS;
const format = process.env.FIGMA_EXPORT_FORMAT || 'png';
const scale = Number(process.env.FIGMA_EXPORT_SCALE || '2');

if (!token || !fileKey || !nodeIdsRaw) {
  console.error('Missing required env vars: FIGMA_ACCESS_TOKEN, FIGMA_FILE_KEY, FIGMA_COMPONENT_NODE_IDS');
  process.exit(1);
}

const nodeIds = nodeIdsRaw
  .split(',')
  .map((id) => id.trim())
  .filter(Boolean);

if (nodeIds.length === 0) {
  console.error('FIGMA_COMPONENT_NODE_IDS must contain one or more comma-separated node ids.');
  process.exit(1);
}

const baseDir = path.resolve('src/assets/figma');
await fs.mkdir(baseDir, { recursive: true });

const imagesUrl = new URL(`https://api.figma.com/v1/images/${fileKey}`);
imagesUrl.searchParams.set('ids', nodeIds.join(','));
imagesUrl.searchParams.set('format', format);
imagesUrl.searchParams.set('scale', String(scale));
imagesUrl.searchParams.set('use_absolute_bounds', 'true');

const imagesRes = await fetch(imagesUrl, {
  headers: { 'X-Figma-Token': token },
});

if (!imagesRes.ok) {
  console.error(`Figma images API failed (${imagesRes.status}):`, await imagesRes.text());
  process.exit(1);
}

const imagesPayload = await imagesRes.json();
const images = imagesPayload.images || {};

const saved = [];
for (const nodeId of nodeIds) {
  const assetUrl = images[nodeId];
  if (!assetUrl) {
    console.warn(`No export URL returned for node ${nodeId}.`);
    continue;
  }

  const assetRes = await fetch(assetUrl);
  if (!assetRes.ok) {
    console.warn(`Failed to download node ${nodeId} (${assetRes.status}).`);
    continue;
  }

  const bytes = Buffer.from(await assetRes.arrayBuffer());
  const fileName = `${nodeId.replace(/[:/]/g, '_')}.${format}`;
  const outPath = path.join(baseDir, fileName);
  await fs.writeFile(outPath, bytes);
  saved.push({ nodeId, fileName });
  console.log(`Saved ${nodeId} -> ${path.relative(process.cwd(), outPath)}`);
}

const indexLines = [
  '// Auto-generated by scripts/figma-sync.mjs',
  '',
];

for (const entry of saved) {
  const varName = `figma_${entry.nodeId.replace(/[^a-zA-Z0-9_]/g, '_')}`;
  indexLines.push(`import ${varName} from './${entry.fileName}';`);
}

indexLines.push('', 'export const figmaAssets = {');
for (const entry of saved) {
  const varName = `figma_${entry.nodeId.replace(/[^a-zA-Z0-9_]/g, '_')}`;
  indexLines.push(`  '${entry.nodeId}': ${varName},`);
}
indexLines.push('} as const;', '', 'export default figmaAssets;', '');

await fs.writeFile(path.join(baseDir, 'generated.ts'), indexLines.join('\n'));
console.log(`Generated ${path.join('src/assets/figma', 'generated.ts')}`);
